# Enable debug logging
debug: true
logging.level.net.runelite: DEBUG

# Development data sources
datasource:
  runelite:
    jndiName:
    driverClassName: org.mariadb.jdbc.Driver
    type: org.mariadb.jdbc.MariaDbDataSource
    url: jdbc:mariadb://192.168.0.69:3306/runelite
    username: runelite
    password: runelite
  runelite-cache:
    jndiName:
    driverClassName: org.mariadb.jdbc.Driver
    type: org.mariadb.jdbc.MariaDbDataSource
    url: jdbc:mariadb://192.168.0.69:3306/runelite-cache
    username: runelite
    password: runelite
  runelite-tracker:
    jndiName:
    driverClassName: org.mariadb.jdbc.Driver
    type: org.mariadb.jdbc.MariaDbDataSource
    url: jdbc:mariadb://192.168.0.69:3306/runelite-tracker
    username: runelite
    password: runelite

# Development mongo
mongo:
  jndiName:
  host: mongodb://192.168.0.69:27017

# Development oauth callback (without proxy)
oauth:
  callback: http://localhost:8080/account/callback
